const data = {
  products: [
    {
      name: 'Nike Shirt',
      slug: 'nike-shirt',
      category: 'Shirt ',
      images: 'frontend/public/images/product.jpeg',
      price: '$10',
      countInStock: 10,
      brand: 'Nike ',
      rating: 5.5,
      numReviews: 10,
      description: 'Button Down Nike Shirt',
    },
    {
      name: 'Adidas',
      slug: 'adidas-shirt',
      category: ' ',
      images: 'frontend/public/images/product.jpeg',
      price: 0,
      countInStock: 10,
      brand: ' ',
      rating: 5.5,
      numReviews: 10,
      description: '',
    },
    {
      name: 'Gucci',
      slug: 'gucci-belt',
      category: ' ',
      price: 0,
      countInStock: 10,
      brand: ' ',
      rating: 5.5,
      numReviews: 10,
      description: '',
    },
    {
      name: 'Super Dry',
      slug: 'superdry-shorts ',
      category: ' ',
      price: 0,
      countInStock: 10,
      brand: ' ',
      rating: 5.5,
      numReviews: 10,
      description: '',
    },
  ],
}

export default data
